### ISSUE TITLE
Механизм пропуска хода

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/PythonBasic1#22]
При попадании на клетку пропуска хода игрок должен пропустить следующий ход.
Подсказка: возможно, для этого имеет смысл создать дополнительный список, в котором для каждого игрока будет устанавливаться признак пропуска хода.

Баллы: 6

**Comment by sanie4eg** [comment]
complete.
Вместо дополнительного списка, добавил в список player четвертое значение, boolean pass_throw
